#
# create htpasswd localhost
#
---
##- hosts: masters
- hosts: masters
  vars:
    pwdfile: /etc/origin/master/htpasswd
    passwd: 'Welkom01'
    users:
      - amy
      - andrew
      - brian
      - betty
  tasks:
    - name: Users are created
      shell: "htpasswd -b {{ pwdfile }} {{ item }} {{ passwd }}"
      with_items:
        - "{{ users }}"
