#
# smoke_test.yaml
#
---
- hosts: localhost
  become: yes
  vars:
    project: smoke-test
    app: nodejs-mongo-persistent
  tasks:
    - name: smoke-test project is created
      shell: "oc new-project {{ project }}"

    - name: nodejs-mongo-persistent app is deployed
      shell: "oc new-app {{ app }} -n {{ project }}"

    - name: "Wait for nodejs-mongo-persistent to be up"
      shell: "oc get pods -n {{ project }} | grep ^{{ app }}"
      register: result
      until: result.stdout.find("Running") != -1
      retries: 5
      delay: 10

    - name: curl nodejs-mongo-persistent app
      shell: "curl -i --head $(oc get route {{ app }} -o jsonpath='{.spec.host}' -n {{ project }})"
      args:
        warn: no

    - name: delete smoke-test project
      shell: "oc delete project {{ project }}"
